In this post I will share an example that uses Principal Component Analysis as a dimension reduction tool to prepare the data for logistic regression prediction in python.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as ex
import plotly.graph_objs as go
import plotly.figure_factory as ff
from plotly.subplots import make_subplots
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [14]:
df=pd.read_csv('/content/finalmerged.csv')
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df = df.drop(['customerid', 'month_approved_loan'], axis = 1)
df = df.dropna()
df.head() # Inspect the first 5 rows

,longitude_gps,latitude_gps,bank_branch_clients,loannumber,loanamount,totaldue,termdays,good_bad_flag,referred,realage,...,employment_status_client_Contract,employment_status_client_Permanent,employment_status_client_Retired,employment_status_client_Self-Employed,employment_status_client_Student,employment_status_client_Unemployed,employment_status_client_Unknown,is_late_for_firstpay,exceeds_loan_term_days,TipoInteres
0,3.319219,6.528604,0,2,10000.0,13000.0,30,1,1,48,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
1,3.325598,7.119403,0,2,10000.0,13000.0,30,0,0,36,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
2,5.746100,5.563174,0,4,10000.0,13000.0,30,1,0,35,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
3,5.746100,5.563174,0,4,10000.0,13000.0,30,1,0,35,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
4,5.746100,5.563174,0,4,10000.0,13000.0,30,1,0,35,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [15]:
x = df.loc[:, df.columns != 'good_bad_flag'] # as x variable - the features
x=StandardScaler().fit_transform(x) # standarize the variables
y=df['good_bad_flag'] # assign y variable - the target

We will start by using only the first 2 leading principal components, and then explore 3 principal components and 4 principal components.

In [29]:
pca=PCA(n_components=2)
PC=pca.fit_transform(x)
principalDF=pd.DataFrame(data=PC,columns=['pc1','pc2'])
finalDf = pd.concat([principalDF, df[['good_bad_flag']]], axis = 1)
finalDf.head()

        pc1       pc2  good_bad_flag
0 -3.802878  0.544418            1.0
1 -3.563865  1.558228            0.0
2 -3.364829  0.927970            1.0
3 -3.364829  0.927970            1.0
4 -3.124634 -0.763975            1.0

To assess how much weightings each feature will have in later predictions, we could construct a loadings table. The loadings shows how much each of our original features have contributed to each of the “new features” — the principal components.

In [31]:
PCloadings = pca.components_.T * np.sqrt(pca.explained_variance_)
components=df.columns.tolist()
components.pop(7)
loadingdf=pd.DataFrame(PCloadings,columns=('PC1','PC2'))
loadingdf["variable"]=components
loadingdf

         PC1       PC2                                  variable
0   0.005484  0.014028                             longitude_gps
1  -0.011942 -0.088894                              latitude_gps
2   0.031941  0.103802                       bank_branch_clients
3   0.845344 -0.089238                                loannumber
4   0.879723 -0.323109                                loanamount
5   0.874249 -0.335063                                  totaldue
6   0.538451 -0.265529                                  termdays
7  -0.324813 -0.050836                                  referred
8   0.003539  0.015882                                   realage
9  -0.877865  0.292460                          TipoInteresAhora
10 -0.025620 -0.010911                      bank_account_Current
11  0.676520  0.407901                        bank_account_Other
12 -0.667388 -0.403375                      bank_account_Savings
13  0.448757  0.421642       level_of_education_clients_Graduate
14  0.209779  0.075844  level_of_education_clients_Post-Graduate
15  0.017307  0.060272        level_of_education_clients_Primary
16  0.138725  0.212035      level_of_education_clients_Secondary
17 -0.544946 -0.503017        level_of_education_clients_Unknown
18 -0.056585 -0.038430              bank_name_client_Access Bank
19  0.043775 -0.040833             bank_name_client_Diamond Bank
20 -0.042282  0.015746                  bank_name_client_EcoBank
21  0.066814 -0.022743                     bank_name_client_FCMB
22 -0.048631 -0.067560            bank_name_client_Fidelity Bank
23 -0.013816 -0.060953               bank_name_client_First Bank
24  0.074677  0.156368                  bank_name_client_GT Bank
25 -0.004348  0.003568            bank_name_client_Heritage Bank
26  0.024526 -0.006499            bank_name_client_Keystone Bank
27 -0.028102  0.010739                bank_name_client_Skye Bank
28 -0.022288 -0.029454             bank_name_client_Stanbic IBTC
29 -0.016031 -0.027683       bank_name_client_Standard Chartered
30 -0.079702  0.051333            bank_name_client_Sterling Bank
31 -0.004573 -0.016654                      bank_name_client_UBA
32  0.010702  0.003872               bank_name_client_Union Bank
33 -0.028291  0.022444               bank_name_client_Unity Bank
34 -0.024701 -0.070431                bank_name_client_Wema Bank
35 -0.021298 -0.046083              bank_name_client_Zenith Bank
36  0.016475 -0.051411         employment_status_client_Contract
37 -0.211443 -0.229064        employment_status_client_Permanent
38  0.027704  0.018714          employment_status_client_Retired
39  0.411242  0.316107    employment_status_client_Self-Employed
40  0.100374  0.021981          employment_status_client_Student
41  0.032306  0.138150       employment_status_client_Unemployed
42 -0.271153 -0.106851          employment_status_client_Unknown
43 -0.106524  0.571643                      is_late_for_firstpay
44 -0.159214  0.585396                    exceeds_loan_term_days
45 -0.648755  0.148323                               TipoInteres

Now we can plot the loadings and see which of them have high weightings in both principal component 1 and 2:

In [38]:
fig=ex.scatter(x=loadingdf['PC1'],y=loadingdf['PC2'],text=loadingdf['variable'],)
fig.update_layout(
height=600,width=500,
title_text='loadings plot')
fig.update_traces(textposition='bottom center')
fig.add_shape(type="line",
x0=-0, y0=-1,x1=-0,y1=1,
line=dict(color="RoyalBlue",width=3)
)
fig.add_shape(type="line",
x0=-1, y0=0,x1=1,y1=0,
line=dict(color="RoyalBlue",width=3)
)
fig.show()

It is clear that is_late_for_first_pay and exceeds_loan_term_days t are two heavily weighted features.